#	$OpenBSD: Makefile,v 1.14 2026/05/31 11:39:44 djm Exp $

SUBDIR=	test_helper sshbuf sshkey bitmap kex hostkeys utf8 match conversion
SUBDIR+=authopt misc pkcs11 sshsig servconf

.include <bsd.subdir.mk>
