#!/bin/sh
#       $OpenBSD: $
#       Written by Simon Josefsson <simon@josefsson.org>
#       Placed in the Public Domain.
#
LICENSE="libmceliece-20230612/doc/license.md"
PEOPLE="libmceliece-20230612/doc/people.md"
FILES="	libmceliece-20230612/include-build/crypto_declassify.h
	libmceliece-20230612/crypto_kem/6688128f/vec/params.h
	libmceliece-20230612/inttypes/crypto_intN.h
	libmceliece-20230612/inttypes/crypto_intN.h
	libmceliece-20230612/inttypes/crypto_intN.h
	libmceliece-20230612/inttypes/crypto_uintN.h
	libmceliece-20230612/inttypes/crypto_uintN.h
	libmceliece-20230612/inttypes/crypto_uintN.h
	libmceliece-20230612/crypto_kem/6688128f/vec/vec.h
	libmceliece-20230612/crypto_kem/6688128f/vec/benes.h
	libmceliece-20230612/crypto_kem/6688128f/vec/bm.h
	libmceliece-20230612/crypto_kem/6688128f/vec/controlbits.h
	libmceliece-20230612/crypto_kem/6688128f/vec/decrypt.h
	libmceliece-20230612/crypto_kem/6688128f/vec/encrypt.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_consts.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_powers.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_scalars_2x.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_scalars_4x.h
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_tr.h
	libmceliece-20230612/crypto_kem/6688128f/vec/gf.h
	libmceliece-20230612/crypto_kem/6688128f/vec/hash.h
	libmceliece-20230612/crypto_kem/6688128f/vec/int32_sort.h
	libmceliece-20230612/crypto_kem/6688128f/vec/operations.h
	libmceliece-20230612/crypto_kem/6688128f/vec/pk_gen.h
	libmceliece-20230612/crypto_kem/6688128f/vec/sk_gen.h
	libmceliece-20230612/crypto_kem/6688128f/vec/transpose.h
	libmceliece-20230612/crypto_kem/6688128f/vec/uint16_sort.h
	libmceliece-20230612/crypto_kem/6688128f/vec/uint64_sort.h
	libmceliece-20230612/crypto_kem/6688128f/vec/util.h
	libmceliece-20230612/crypto_xof/shake256/unrollround/shake256.c
	libmceliece-20230612/crypto_xof/shake256/unrollround/keccak.inc
	libmceliece-20230612/crypto_kem/6688128f/vec/benes.c
	libmceliece-20230612/crypto_kem/6688128f/vec/bm.c
	libmceliece-20230612/crypto_kem/6688128f/vec/controlbits.c
	libmceliece-20230612/crypto_kem/6688128f/vec/decrypt.c
	libmceliece-20230612/crypto_kem/6688128f/vec/encrypt.c
	libmceliece-20230612/crypto_kem/6688128f/vec/shared-fft_consts.c
	libmceliece-20230612/crypto_kem/6688128f/vec/shared-fft_powers.c
	libmceliece-20230612/crypto_kem/6688128f/vec/shared-fft_scalars_2x.c
	libmceliece-20230612/crypto_kem/6688128f/vec/shared-fft_scalars_4x.c
	libmceliece-20230612/crypto_kem/6688128f/vec/fft.c
	libmceliece-20230612/crypto_kem/6688128f/vec/fft_tr.c
	libmceliece-20230612/crypto_kem/6688128f/vec/gf.c
	libmceliece-20230612/crypto_kem/6688128f/vec/kem_dec.c
	libmceliece-20230612/crypto_kem/6688128f/vec/kem_enc.c
	libmceliece-20230612/crypto_kem/6688128f/vec/kem_keypair.c
	libmceliece-20230612/crypto_kem/6688128f/vec/pk_gen.c
	libmceliece-20230612/crypto_kem/6688128f/vec/sk_gen.c
	libmceliece-20230612/crypto_kem/6688128f/vec/vec.c
	libmceliece-20230612/crypto_kem/6688128f/vec/wrap_dec.c
	libmceliece-20230612/crypto_kem/6688128f/vec/wrap_enc.c
	libmceliece-20230612/crypto_kem/6688128f/vec/wrap_keypair.c"
###

set -e
cd $1
echo -n '/*  $'
echo 'OpenBSD: $ */'
echo
echo '/*'
sed -e 's/^/ * /' < $LICENSE
echo ' *'
sed -e 's/^/ * /' < $PEOPLE
echo ' *'
echo ' * This file is generated by mceliece6688128f.sh from these files:'
echo ' *'
echo "$FILES" | sed -e 's/\t/ * /'
echo ' *'
echo ' */'
echo
echo '#include "includes.h"'
echo
echo '#if USE_MCELIECE6688128X25519 && !USE_LIBMCELIECE'
echo
echo '#include <string.h>'
echo '#include "crypto_api.h"'
echo
# Map the types used in this code to the ones in crypto_api.h.  We use #define
# instead of typedef since some systems have existing intXX types and do not
# permit multiple typedefs even if they do not conflict.
for t in int8 uint8 int16 uint16 int32 uint32 int64 uint64; do
	echo "#define $t crypto_${t}"
done
echo
N=16
for i in $FILES; do
	echo "/* from $i */"
	# Changes to all files:
	#  - remove all includes, we inline everything required.
	#  - make functions not required elsewhere static.
	#  - rename the functions we do use.
	#  - remove unnecessary defines and externs.
	sed -e "/#include/d" \
	    -e "s/crypto_kem_/crypto_kem_mceliece6688128f_/g" \
	    -e "s/crypto_xof(/crypto_xof_shake256(/g" \
	    -e "s/^void /static void /g" \
	    -e "s/^int /static int /g" \
	    -e "s/^static void crypto_kem_/void crypto_kem_/g" \
	    -e "s/^static int crypto_kem_/int crypto_kem_/g" \
	    -e "s/^int16 /static int16 /g" \
	    -e "s/^uint16 /static uint16 /g" \
	    -e "/^extern /d" \
	    -e "/perm_check/d" \
	    -e '/CRYPTO_NAMESPACE/d' \
	    -e '/CRYPTO_SHARED_NAMESPACE/d' \
	    -e 's/[	 ]*$//' \
	    $i | \
	case "$i" in
	# Use int64_t for intermediate values in int32_MINMAX to prevent signed
	# 32-bit integer overflow when called by crypto_sort_uint32.
	*/int32_sort.h)
	    sed -e "s/int32_t ab = b ^ a/int64_t ab = (int64_t)b ^ (int64_t)a/" \
	        -e "s/int32_t c = b - a/int64_t c = (int64_t)b - (int64_t)a/"
	    ;;
	# Silence false-alarm gcc warning about unitialized variable.
	*/kem_keypair.c)
	    sed -e "s/uint64_t pivots;/uint64_t pivots = 0;/"
	    ;;
	# This file clobbers namespace for one-letter variable names.
	*/controlbits.c)
	    cat
	    echo '#undef A'
	    echo '#undef B'
	    echo '#undef q'
	    ;;
	# Uses variable B0 which is used for termios B0 control flag.
	*/shake256.c)
	    echo 'static void keccak(uint64_t *s);'
	    echo '#undef B0 /* /usr/include/asm-generic/termbits.h */'
	    cat
	    ;;
	# Poor-man's #include now that we removed all #include's above.
	*/shared-fft_*.c)
	    INC=$(echo $i | sed -e "s,/shared-fft_,/," -e "s,.c$,.data,")
	    DATA=$(echo $(cat $INC))
	    sed -e "s/};/$DATA\n};/"
	    ;;
	# Create three different versions of file depending on N.
	*/crypto_*intN.h)
	    sed -e "s/N/$N/g"
	    ;;
	# Default: pass through.
	*)
	    cat
	    ;;
	esac
	echo
	if test "$N" = 16; then
	    N=32
	elif test "$N" = 32; then
	    N=64
	elif test "$N" = 64; then
	    N=16
	fi
done
echo '#endif /* USE_MCELIECE6688128X25519 && !USE_LIBMCELIECE */'
