# escape=`
#0.3.6 (no powershell 6)
FROM balu1202/openssh-dockerbuildimage-ltsc2019-new:latest

SHELL ["PowerShell.exe", "-command"]
RUN Set-ExecutionPolicy Unrestricted

COPY ./OpenSSH-build.ps1 /OpenSSH-build.ps1

ENTRYPOINT ["powershell", "-executionpolicy", "unrestricted"]
