name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: keygen1
      run: ./ssh-keygen -t ecdsa -f foo -P foofoo
    - name: keygen2
      run: ./ssh-keygen -p -m PEM -f foo -P foofoo
    - name: keygen3
      run: ./ssh-agent -s && ./ssh-add foo
